import "./globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";

export const metadata = {
  title: "Kava UP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialTheme = 'pink';
  return (
    <ThemeProvider initialTheme={initialTheme}>
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </ThemeProvider>
  );
}
