"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { useTheme } from '../components/common/UseTheme'
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { theme, toggleTheme } = useTheme();

  useEffect(() => {
    const link = document.getElementById('theme-link');
    if (link) {
      link.href = `/themes/${theme}.css`;
    }
  }, [theme]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <button onClick={toggleTheme}>Toggle Theme</button>
        </header>
        <main>{children}</main>
        <link id="theme-link" rel="stylesheet" type="text/css" href={`/themes/${theme}.css`} />
      </body>
    </html>
  );
}
