import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";


const poppins = Poppins({
  subsets: ["latin"],
  variable: '--font-poppins',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Kava UP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialTheme = 'pink';
  return (
    <ThemeProvider initialTheme={initialTheme}>
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </ThemeProvider>
  );
}
